title: Leo-0 # site title
author: 
    name: Leo-0 # your name
    avatar: '/images/whale.jpg' # your avatar url
brand:  
    url: '/images/fight.gif' # brand url
description: 
    学无止境，好好学习，天天向上。此为github pages + jekyll 搭建的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social settings
github_username: Leo-0
email: leo_yanlin@163.com

# Permalink
permalink: /:categories/:title

# Personalized signature 
personalized: 
    - signature: 拥抱生活，热爱生活
    - signature: enjoy coding

# Navigation
nav: 
    - {title: 首页, url: '/'}
    - {title: 关于, url: '/about'}
    - {title: 文章, url: '/archive'}
    - {title: 收藏夹, url: '/collection'}
    - {title: 相册, url: '/photo'}
    - {title: 标签, url: '/tag'}
    - {title: 留言, url: '/message'}

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginator
paginate: 6

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
