title: 呀,Leo-0的小站~ # site title
author: Leo-0 # your name
brand:  
    url: '/images/Leo-0.png' # brand url
description: 
    学无止境，好好学习，天天向上。此为github pages + jekyll 搭建的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
jekyllrb: "https://jekyllrb.com/"

defaults:
  - 
   scope:
      path: "images/albums"
   values:
      album: true

# Social settings
github_username: Leo-0
email: no@email.com

# Permalink
permalink: /blog/:categories/:title

# Personalized signature 
personalized: 
    - signature: 拥抱生活，热爱生活

saying: 
    - When other men blindly follow the truth
    - Remember
    - Nothing is true
    - When other men are limited by morality or law
    - Remember
    - Everything is permitted
# Navigation
nav: 
    - {title: 首页, url: '/'}
    - {title: 归档, url: '/archive'}
    - {title: 标签, url: '/tags'}
    - {title: 关于, url: '/about'}

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginator
paginate: 10
paginate_path: 'blog/page:num'

# Baidu Analysis
# baidu-analysis:
#    enable: true
baidu-analysis: 3df3daf643a33650a558775016d1291a
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
